### PR TITLE
add slconn begin/end times and override logging

### PR DESCRIPTION
**Pull request by ozym**
@gclitheroe a couple of updates towards #11
(untested against a real endpoint though).

For `slconn.SLCD` I've added:

```
SetBeginTime(string)
BeginTime() string
SetEndTime(string)
EndTime() string
```

I've left them as string args, rather than a time.Time which would require extra error handling. This could be done if required (just a style thing at the moment).

For the `slconn `package

`LogInt(int, func(string), func(string))`

Is an attempt to either quieten down the logging, or at least provide a mechanism to log error messages etc.

I've updated the `slconn_test.go` file and swapped a number of Errors for Fatals.

### CODE REVIEW

**Comment by gclitheroe** [comment]
@danieldooley -  if you have time please could you try out this pr?  The main goal is to be able to set the start time for a data request to SEEDLink.  This means when a long running process needs restarting we can request some time overlap to cover the restart e.g., something like `now - 10 mins` for the start time and then continue to stream all data (no end time).

Mark says the code changes are simple but testing against a server makes sense - he's not sure this always works well.

**Comment by danieldooley** [comment]
@geoff - I've given the `SetBeginTime` a quick test with some code I already had, seems to work just fine against `link.geonet.org.nz:18000`.

Throws these warnings though:
```
../../../../GeoNet/kit/slink/slconn.go:8:38: warning: implicit declaration of function 'logPrint' is invalid in C99 [-Wimplicit-function-declaration]
../../../../GeoNet/kit/slink/slconn.go:9:38: warning: implicit declaration of function 'errPrint' is invalid in C99 [-Wimplicit-function-declaration]
```

**Comment by ozym** [comment]
Ah, the warnings hopefully will go away if the extra declarations are added to the start of the slconn.go file.
e.g. just before the line that calls them.

//void logPrint(const char *message);
//void errPrint(const char *message);

**Comment by ozym** [comment]
@danieldooley hopefully it should compile without warnings now ...

**Comment by danieldooley** [comment]
@ozym yeah that's fixed it.

**Comment by gclitheroe** [comment]
merged this in over here https://github.com/GeoNet/kit/pull/18

**Pull request closed without merging**
