### PR TITLE
chore: use Go 1.20

### PR DESCRIPTION
**Pull request by BobyMCbobs**
## Proposed Changes

Resolves https://github.com/GeoNet/kit/actions/runs/5351075205/jobs/9704474939?pr=137.

Changes proposed in this pull request:

- use Go 1.20
- vendor dependencies
- fix govulncheck errors (https://github.com/GeoNet/kit/actions/runs/5351075205/jobs/9704474939?pr=137)

## Production Changes

The following production changes are required to deploy these changes:

- None

## Review

Check the box that applies to this code review.  If necessary please seek help with adding a checklist guide for the reviewer.
When assigning the code review please consider the expertise needed to review the changes.

- [ ] This is a content (documentation, web page etc) only change.
- [x] This is a minor change (meta data, bug fix, improve test coverage etc).
- [ ] This is a larger change (new feature, significant refactoring etc).  Please use the code review guidelines to add a checklist below to guide the code reviewer.

### Code Review Guide

- [ ] build dependents using this version

### CODE REVIEW

**Comment by junghao** [comment]
Hi, can we not upgrade this critical open source package so aggressive please?
This repo changes will affect every services we've been using. Which requires a checklist to upgrade : https://github.com/GeoNet/tickets/issues/11780.

**Comment by BobyMCbobs** [comment]
> Hi, I'd suggest that we have a discussion regarding the upgrade of this repo. This repo changes will affect every services we've been using. Which requires a checklist to upgrade : [GeoNet/tickets#11780](https://github.com/GeoNet/tickets/issues/11780).

@junghao, my intention is to resolve the govulncheck issues, which seems to be through requiring being on the latest Go.
Happy to figure out the next steps as I think it'd be important to upgrade

**Comment by BobyMCbobs** [comment]
OK, now it appears to be failing due to the _io/ioutil_ deprecation
https://app.travis-ci.com/github/GeoNet/kit/builds/264098250

**Comment by BobyMCbobs** [comment]
Commands to remove ioutil references

```
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,\t\"io/ioutil\"\n,,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.ReadFile,os.ReadFile,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.ReadDir,os.ReadDir,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.ReadAll,io.ReadAll,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.WriteFile,os.WriteFile,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.NopCloser,io.NopCloser,g" {}
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} sed -i -z "s,ioutil.TempFile,os.CreateTemp,g" {}
go install golang.org/x/tools/cmd/goimports@latest
find . -type f -name '*.go' -not -path './vendor/*' | xargs -I{} goimports -w {}
```

**Comment by BobyMCbobs** [comment]
closing for now to get by with #141

**Pull request closed without merging**
