### PR TITLE
feat: add ability to send/receive message attributes

### PR DESCRIPTION
**Pull request by wilsonjord**
## Proposed Changes

Resolves #14687

Changes proposed in this pull request:

- Add ability to send/receive message attributes

## Production Changes

The following production changes are required to deploy these changes:

- None

## Review

Check the box that applies to this code review.  If necessary please seek help with adding a checklist guide for the reviewer.
When assigning the code review please consider the expertise needed to review the changes.

- [ ] This is a content (documentation, web page etc) only change.
- [ ] This is a minor change (meta data, bug fix, improve test coverage etc).
- [x] This is a larger change (new feature, significant refactoring etc).  Please use the code review guidelines to add a checklist below to guide the code reviewer.

### CODE REVIEW

**Review by junghao — COMMENTED** [review]
This looks convenient at a glance. 

However, I can see that what you’re trying to achieve with these code is to wrap and form a structure below:
```
sqs.SendMessageInput{
  QueueUrl,
  MessageBody,
  DelaySeconds: someValue,
  MessageAttributes: {
    DataType: sometype,
  StringValue: someValue,
  },
  MessageGroupId: someid,
  MessageDeduplicationId: someid,
}
```
Without your wrapping functions, then send the structure along with the command, which is about 7 extra lines of code (queueUrl and messageBody doesn’t count).

Not sure if this is worth it.

**Comment by wilsonjord** [comment]
> This looks convenient at a glance.
> 
> However, I can see that what you’re trying to achieve with these code is to wrap and form a structure below:
> 
> ```
> sqs.SendMessageInput{
>   QueueUrl,
>   MessageBody,
>   DelaySeconds: someValue,
>   MessageAttributes: {
>     DataType: sometype,
>     StringValue: someValue,
>   },
>   MessageGroupId: someid,
>   MessageDeduplicationId: someid,
> }
> ```

Correct - that is what all the functions (current and proposed) are doing...constructing `sqs.SendMessageInput` in a user-friendly manner.

> Without your wrapping functions, then send the structure along with the command

How do you mean? You mean send the "message attributes structure"? If so, I investigated this initially, and wasn't happy with it in terms of answering my questions:
- how can I send message attributes with a message?
- how can I send message attributes with a delay?
- how can I send message attributes to a FIFO queue?
- how can I send message attributes to a FIFO queue with a delay?

My PR hopes to save code in the long term, but also reduce proliferation of functions with noisy signatures.

**Comment by junghao** [comment]
How about we simply create a function called `SendWithParameters()` to reflect existing `Send()`, and it accepts `sqs.SendMessageInput` as the extra parameter?

**Comment by wilsonjord** [comment]
General feedback is no strong usercase for this design pattern at this stage. Branch will be kept for reference.

**Comment by CallumNZ** [comment]
I like it.
Compared to the `WithParameters` suggestion, not having to directly import/fill out the whole Input struct is nice, especially when there's just one field you want to add (which I think is often the case if not just using default).

**Pull request closed without merging**
